# Generated by Django 5.2.12 on 2026-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField()),
                ('titre_1', models.CharField(max_length=300)),
                ('paragraphe_1', models.TextField()),
                ('titre_2', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraphe_2', models.TextField(blank=True, null=True)),
                ('titre_3', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraphe_3', models.TextField(blank=True, null=True)),
                ('titre_4', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraphe_4', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
