# Generated by Django 5.2.12 on 2026-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titre_article',
            field=models.CharField(max_length=500),
        ),
    ]
