# Generated by Django 5.2.12 on 2026-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_titre_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
